
import bcrypt from 'bcryptjs';
const data = {
    users: [
        {
            name: 'John',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            name: 'Jane',
            email: 'user@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'Adidas',
            rating: 3.2,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 90,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 3,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 90,
            brand: 'Oliver',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description: 'Smart looking pants',
        },
        {
            name: 'Fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 95,
            brand: 'Zara',
            rating: 3.5,
            numReviews: 7,
            countInStock: 20,
            description: 'A popular pants',
        },
        {
            name: 'Classic Pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 75,
            brand: 'Casely',
            rating: 2.4,
            numReviews: 14,
            countInStock: 20,
            description: 'A popular pants',
        },
        {
            name: 'Hand-Bag',
            slug: 'hand-Bag',
            category: 'Bags',
            image: '/images/BAG1.jpg',
            price: 200,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular bag',
        },
        {
            name: 'Hand Bag style',
            slug: 'hand Bag style',
            category: 'Bags',
            image: '/images/BAG2.png',
            price: 500,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular bag',
        },
        {
            name: 'Hand Bag popular',
            slug: 'hand Bag popular',
            category: 'Bags',
            image: '/images/BAG3.png',
            price: 400,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular bag',
        },
        {
            name: 'Makeup kit',
            slug: 'makeup kit',
            category: 'kit',
            image: '/images/kit1.jpg',
            price: 1500,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular kit',
        },
        {
            name: 'Makeup kit popular',
            slug: 'makeup kit popular',
            category: 'kit',
            image: '/images/kit2.jpg',
            price: 2500,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular kit',
        },
        {
            name: 'Smooth makeup-kit',
            slug: 'smooth makeup-kit',
            category: 'kit',
            image: '/images/kit3.jpg',
            price: 700,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular kit',
        },
        {
            name: 'Smart Watch',
            slug: 'smart Watch',
            category: 'Watch',
            image: '/images/watch.jpg',
            price: 700,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular Smart Watch',
        },
        {
            name: 'Beautiful saree',
            slug: 'beautiful saree',
            category: 'Saree',
            image: '/images/saree.jpg',
            price: 700,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A Beautiful saree',
        },
        {
            name: 'Saree',
            slug: 'saree',
            category: 'Saree',
            image: '/images/saree2.jpg',
            price: 1000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular Smart Watch',
        },
        {
            name: 'Flexible kurti',
            slug: 'flexible kurti',
            category: 'Kurti',
            image: '/images/kurti.jpg',
            price: 700,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular Kurti',
        },
        {
            name: 'Kurti',
            slug: 'kurti',
            category: 'Kurti',
            image: '/images/kurti2.jpg',
            price: 1000,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A beautiful kurti',
        },
    ],
};

export default data;